config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get "help" => "static_pages#help"
  devise_for :users, path_prefix: "d",
    controllers: {omniauth_callbacks: Settings.auth_callback}
  resources :subjects

  resources :users do
    resources :questions
  end
  resources :exams
  namespace :admin do
    root "static_pages#admin_home"
    resources :subjects
    resources :users
    resources :exams
    resources :questions
  end
end

app/models/question.rb
class Question < ActiveRecord::Base
  include StateAble
  include PublicActivity::Model

  acts_as_paranoid
  before_destroy :update_question_as_deleted

  belongs_to :subject
  belongs_to :user
  enum status: {waiting: 0, approved: 1, edited: 2, deleted: 3}
  enum question_type: {single: 0, multiple: 1, text: 2}

  has_many :answers, dependent: :destroy
  has_many :results, dependent: :destroy
  has_many :exams, through: :results

  def update_question_as_deleted
    self.update_status :deleted
  end

  accepts_nested_attributes_for :answers, allow_destroy: true,
    reject_if: proc {|answer| answer[:content].blank?}

  validates :content, presence: true
  validates :answers, presence: true
end

app/controllers/admin/questions_controller.rb
class Admin::QuestionsController < Admin::BaseController
  load_resource

  def new
    @subjects = Subject.all
    @question.answers.build
  end

  def create
    if @question.save
      flash[:sucess] = t "questions.success"
    else
      flash[:danger] = t "questions.fail"
    end
    redirect_to :back
  end

  def index
    @q = Question.with_deleted.ransack params[:q]
    option = params[:option].nil? ? Settings.questions.all : params[:option]
    @questions = @q.result.includes(:subject).send(option).page(params[:page])
      .per Settings.pagination.questions_per_page
  end

  def edit
    @subjects = Subject.all
    @question.answers.build
  end

  def update
    if @question && @question.update_attributes(question_params)
      flash[:sucess] = t "questions.success"
    else
      flash[:danger] = t "questions.fail"
      render :edit
    end
    respond_to do |format|
      format.html {redirect_to admin_questions_path}
      format.js
    end
  end

  def destroy
    if @question.really_destroy!
      flash[:success] = t "questions.success"
    else
      flash.now[:danger] = t "questions.fail"
    end
    redirect_to :back
  end

  private
  def question_params
    params.require(:question).permit :question_type, :content, :subject_id,
      :user_id, :status, answers_attributes: [:id,
      :is_correct, :content, :_destroy]
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  load_and_authorize_resource

  def new
    @subjects = Subject.all
    @question.answers.build
  end

  def create
    if @question.save
      flash[:sucess] = t "questions.success"
    else
      flash[:danger] = t "questions.fail"
    end
    redirect_to :back
  end

  def index
    option = params[:option].nil? ? Settings.questions.all : params[:option]
    @questions = current_user.questions.send(option).page(params[:page])
      .per Settings.pagination.questions_per_page
  end

  def edit
    @subjects = Subject.all
    @question.answers.build
  end

  def update
    if @question && @question.update_attributes(question_params)
      flash[:sucess] = t "questions.success"
      redirect_to user_questions_path current_user
    else
      flash[:danger] = t "questions.fail"
      render :edit
    end
  end

  def destroy
    if @question.destroy
      flash[:success] = t "questions.success"
    else
      flash.now[:danger] = t "questions.fail"
    end
    redirect_to :back
  end

  private
  def question_params
    params.require(:question).permit :question_type, :content, :subject_id,
      :user_id, answers_attributes: [:id,
      :is_correct, :content, :_destroy]
  end
end

app/helpers/admin/questions_helper.rb
module Admin::QuestionsHelper
end

app/views/questions/_answer_form.html.erb
<div class="panel panel-info fields">
  <div class="panel-body">
    <%= f.text_field :content, class: "form-control word_content" %>
    <%= f.check_box :is_correct, class: "radio_answer" %>
    <%= f.label :is_correct, t("questions.is_correct"),
      class: "correct_answer" %>
    <%= link_to_remove_fields raw("<span class='glyphicon glyphicon-remove'></span>"),
      f %>
  </div>
</div>

app/views/questions/_form.html.erb
<%= form_for [current_user, @question] do |f| %>
  <%= render "shared/error_messages", object: f.object %>
  <%= f.hidden_field :user_id, value: current_user.id %>
  <%= f.hidden_field :status, value: :waiting %>

  <%= f.label :subject %>
  <%= f.select :subject_id,
    options_from_collection_for_select(@subjects, :id, :name, params[:subject_id]),
    {}, {class: "form-control"} %>

  <%= f.label :content %>
  <%= f.text_field :content, class: "form-control" %>

  <%= f.label :question_type %>
  <%= f.select :question_type, Question.question_types.keys.to_a, {selected: "0"},
    {class: "form-control"} %>

  <%= f.label :answer %>
  <div id="choice">
    <div id="answers">
      <%= f.fields_for :answers do |answer| %>
        <div class="answers">
          <%= render "answer_form", f: answer %>
        </div>
      <% end %>
    </div>
    <div class="col-md-offset-0 col-md-1">
      <%= link_to_add_fields raw("#{t :add}"), f, :answers %>
      <br>
    </div>
  </div>
  <div id="text">
    <%= f.fields_for :answers do |answer| %>
      <%= answer.text_field :content, class: "form-control" %>
    <% end %>
  </div>

  <%= f.submit t("questions.create"), class: "btn btn-primary" %>
<% end %>

app/views/questions/_question.html.erb
<tr>
  <td><%= question.content %></td>
  <td><%= question.subject.name %></td>
  <td>
    <span class = "label label-<%= question_status_label(question.status) %>">
      <%= question.status %>
    </span>
  </td>
  <td>
    <%= link_to "", edit_user_question_path(current_user, question.id),
     class: "btn btn-warning btn-md glyphicon glyphicon-edit" %>
    <%= link_to "", user_question_path(current_user.id, question.id),
      method: :delete, data: {confirm: t("questions.confirm")},
      class: "btn btn-danger btn-md glyphicon glyphicon-trash" %>
  </td>
</tr>

app/views/questions/edit.html.erb
<% provide :title, t("questions.edit") %>
<h2><%= t "questions.edit" %></h2>
<div class="row">
  <%= render "form" %>
</div>

app/views/questions/index.html.erb
<% provide :title, t("questions.show") %>
<h2><%= t "questions.show" %></h2>
<h3>
  <%= form_for user_questions_path(current_user), method: :get do |f| %>
    <div class="row">
      <% Settings.questions.options.each do |option| %>
        <div class="filter">
          <%= radio_button_tag :option, option,
            (checked = true if params[:option] == option),
              class: "radio_answer", value: option %>
          <%= option %>
        </div>
      <% end %>
      <p>
        <div class="col-md-offset-3 col-md-2">
          <%= f.submit t("questions.filter"),
            class: "btn btn-primary form-control"%>
        </div>
      </p>
    </div>
  <% end %>
</h3>
<table class="table">
  <thead>
    <tr>
      <th><%= t "questions.content" %></th>
      <th><%= t "questions.subject" %></th>
      <th><%= t "questions.status" %></th>
    </tr>
  </thead>
  <tbody>
    <%= render @questions %>
  </tbody>
</table>
<div>
  <%= link_to t("questions.new"), new_user_question_path(current_user),
    class: "btn btn-success" %>
</div>
<%= paginate @questions %>