config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get "help" => "static_pages#help"
  devise_for :users, path_prefix: "d",
    controllers: {omniauth_callbacks: Settings.auth_callback}
  resources :subjects

  resources :users do
    resources :questions
  end
  resources :exams
  namespace :admin do
    root "static_pages#admin_home"
    resources :subjects
    resources :users
    resources :exams
    resources :questions
  end
end

app/models/exam.rb
class Exam < ActiveRecord::Base
  include PublicActivity::Model
  tracked owner: Proc.new {|controller, model| controller.current_user ?
    controller.current_user : nil}

  after_update :send_exam_noti
  belongs_to :subject
  belongs_to :user

  has_many :results, dependent: :destroy
  has_many :questions, through: :results
  enum status: [:start,:uncheck,:checked]

  accepts_nested_attributes_for :results

  validate :generate_question, on: :create

  class << self
    def to_csv options = {}
      CSV.generate options do |csv|
        csv << column_names
        all.each do |exam|
          csv << exam.attributes.values_at(*column_names)
        end
      end
    end

    def check_exam_daily
      Exam.all.each do |exam|
        if exam.start? && Time.now - exam.created_at > 8.hours
          exam.destroy
        end
        if exam.start? && Time.now - exam.created_at < 8.hours
          UserMailer.send_exam_reminder(exam).deliver_now
        end
      end
    end

    def check_exam_monthly
      Exam.all.each do |exam|
        if exam.start? && Time.now - exam.created_at > 8.hours
          exam.destroy
        end
      end
    end
  end

  def time_remaining
    Settings.exam.time_in_minutes * Settings.exam.sec -
      (Time.zone.now - self.created_at).to_i
  end

  def question_correct
    correct = self.results.where(is_correct: 1).size
    total = self.questions.size
    [correct, total].join("/")
  end

  def send_exam_noti
    SendExamNoti.perform_async self.id
  end

  private
  def generate_question
    self.questions = self.subject.questions.approved
      .order("RANDOM()").limit Settings.exam.questions_per_exam
    errors.add :create, I18n.t("exam.create_exam_fail") if self.subject
      .questions.approved.size == 0
  end
end

app/controllers/admin/exams_controller.rb
class Admin::ExamsController < Admin::BaseController
  load_resource

  def index
    option = params[:option].nil? ? Settings.exam.all : params[:option]
    @exams =  Exam.send(option).page(params[:page])
      .per Settings.pagination.exams_per_page
    respond_to do |format|
      format.html
      format.csv {send_data @exams.to_csv}
      format.xls
    end
  end

  def show
  end

  def create
    @exam.user_id = current_user.id
    if @exam.save
      flash[:success] = t "exam.create_exam_complete"
      redirect_to @exam
    else
      flash[:danger] = @exam.errors.full_messages.join(", ")
      redirect_to admin_subjects_path
    end
  end

  def update
    if @exam.update exam_params
      flash[:success] = t "admin.exam.checked_success"
    else
      flash[:danger] = t "admin.exam.checked_failed"
    end
    redirect_to @exam
  end

  private
  def exam_params
    params.require(:exam).permit :subject_id, :status, results_attributes: [:id, :is_correct]
  end
end

app/controllers/exams_controller.rb
class ExamsController < ApplicationController
  load_and_authorize_resource

  def index
  end

  def show
    @time_remain = @exam.time_remaining
  end

  def create
    @exam.user_id = current_user.id
    if @exam.save
      flash[:success] = t "exam.create_exam_complete"
      redirect_to @exam
    else
      flash[:danger] = @exam.errors.full_messages.join(", ")
      redirect_to subjects_path
    end
  end

  def update
    if @exam.update_attributes exam_params
      flash[:success] = t "exam.create_exam_complete"
    else
      flash[:danger] = t "exam.create_exam_fail"
    end
    redirect_to @exam
  end

  private
  def exam_params
    params.require(:exam).permit :user_id, :status, :subject_id, results_attributes: [
      :id, content_answer: []]
  end
end

app/views/admin/exams/_check_form.html.erb
<li>
  <%= f.object.question.content %>
</li>
<ol type="a">
  <% case f.object.question.question_type %>
  <% when Settings.questions.type.single %>
    <% f.object.question.answers.each do |answer| %>
      <%= f.radio_button :content_answer, answer.id,
        {checked: f.object.content_answer.include?(answer.id.to_s),
        multiple: true, disabled: true, class: "radio_answer"} %>
      <%= answer.content %><br/>
    <% end %>
  <% when Settings.questions.type.multiple %>
    <% f.object.question.answers.each do |answer| %>
      <%= f.check_box :content_answer,
        {checked: f.object.content_answer.include?(answer.id.to_s),
        multiple: true, disabled: true, class: "radio_answer"}, answer.id, false %>
      <%= answer.content %><br/>
    <% end %>
  <% when Settings.questions.type.text %>
    <%= f.text_field :content_answer, {multiple: true, disabled: true} %>
  <% end %>
</ol>
<div class="checkbox">
  <label>
    <%= f.check_box :is_correct %> <%= t "admin.exam.is_correct" %>
  </label>
</div>

app/views/admin/exams/_exam.html.erb
<tr>
  <td> <%= link_to exam.user.name, exam.user %> </td>
  <td> <%= "#{t("exam.name")} #{exam.id}" %> </td>
  <td>
    <span class = "label label-<%= exam.checked? ? "success" : "danger" %>">
      <%= exam.status %>
    </span>
  </td>
  <td> <%= link_to "", admin_exam_path(exam), class: "glyphicon
    glyphicon-edit" unless exam.start? %> </td>
</tr>

app/views/admin/exams/_exam_check.html.erb
  <div class="panel panel-success">
    <div class="panel-heading">
      <h4 class="text-center">
        <%= t "subject.name" %>:
        <%= link_to @exam.subject.name, @exam.subject %>
      </h4>
    </div>
  </div>
  <div class="panel-body">
    <p>
      <%= form_for [:admin, @exam] do |f| %>
      <%= f.hidden_field :status, value: :checked %>
      <ol>
        <%= f.fields_for :results do |result| %>
          <%= render "check_form", f: result %>
        <% end %>
      </ol>
      <div class="row">
        <div class="col-md-2 col-md-offset-5">
          <%= f.submit t("exam.submit"), class: "btn btn-info" unless @exam.start? %>
        </div>
      </div>
      <% end %>
    </p>
  </div>

app/views/admin/exams/_exam_result.html.erb
<div class="panel panel-success">
  <div class="panel-heading">
    <h4 class="text-center">
      <%= t "subject.name" %>:
      <%= link_to @exam.subject.name, @exam.subject %>
    </h4>
  </div>
  <div class="panel-body">
    <p>
      <%= t "admin.exam.result" %>: <%= @exam.question_correct %>
    </p>
    <p>
      <ol>
        <% @exam.results.each do |result| %>
          <li>
            <%= result.question.content %>
          </li>
          <%= form_for [:admin, @exam] do |f| %>
              <% case result.question.question_type %>
              <% when Settings.questions.type.single %>
                <% result.question.answers.each do |answer| %>
                  <%= f.radio_button :content_answer, answer.id,
                    {checked: result.content_answer.include?(answer.id.to_s),
                    multiple: true, disabled: true, class: "radio_answer"} %>
                <%= answer.content %><br/>
              <% end %>
              <% when Settings.questions.type.multiple %>
                <% result.question.answers.each do |answer| %>
                  <%= f.check_box :content_answer, {checked: result.content_answer
                    .include?(answer.id.to_s),
                    multiple: true, disabled: true, class: "radio_answer"},
                    answer.id, false %>
                  <%= answer.content %><br/>
              <% end %>
              <% when Settings.questions.type.text %>
                <%= text_field_tag :content_answer, result.content_answer,
                  disabled: true %>
              <% end %>
            <% unless result.is_correct? %>
              <div class="result_false">
                <%= t "false_answer" %>
              </div>
            <% else %>
              <div class="result_true">
                <%= t "true_answer" %>
              </div>
            <% end %>
            <br><br>
          <% end %>
        <% end %>
        </ol>
    </p>
  </div>
</div>

app/views/admin/exams/index.html.erb
<% provide :title, t("admin.exam.title") %>
<h1> <%= t "admin.exam.title" %> </h1>
<h4>
  <%= form_for admin_exams_path(current_user), method: :get do |f| %>
    <div class="row">
      <% Settings.exam.option.each do |option| %>
        <div class="col-md-2">
          <%= radio_button_tag :option, option,
            (checked = true if params[:option] == option),
            class: "radio_exams", value: option %>
          <%= option %>
        </div>
      <% end %>
      <div class="col-md-off-set-4 col-md-2">
        <%= f.submit t("admin.exam.filter"),
          class: "btn btn-primary form-control"%>
      </div>
    </div>
  <% end %>
</h4>
<div id="section_admin_exam">
  <table id="exam" class="table table-bordered">
    <tbody>
      <tr>
        <th><%= t "admin.exam.name" %></th>
        <th><%= t "admin.exam.exams" %></th>
        <th><%= t "admin.exam.status" %></th>
        <th><%= t "admin.exam.check" %></th>
      </tr>
      <tr>
        <%= render @exams %>
      </tr>
    </tbody>
  </table>
</div>
<%= paginate @exams %>
<p>
  <%= t("export.dl") %>
  <%= link_to t("export.csv"), admin_exams_path(format: "csv") %> |
  <%= link_to t("export.xls"), admin_exams_path(format: "xls") %>
</p>

app/views/admin/exams/index.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Sheet1">
    <Table>
      <Row>
        <Cell>
          <Data ss:Type="String">
            <%= t("admin.exam.id") %>
          </Data>
        </Cell>
        <Cell>
          <Data ss:Type="String">
            <%= t("admin.exam.subect_id") %>
          </Data>
        </Cell>
        <Cell>
          <Data ss:Type="String">
            <%= t("admin.exam.user_id") %>
          </Data>
        </Cell>
        <Cell>
          <Data ss:Type="String">
            <%= t("admin.exam.status") %>
          </Data>
        </Cell>
        <Cell>
          <Data ss:Type="String">
            <%= t("admin.exam.score") %>
          </Data>
        </Cell>
      </Row>
    <% @exams.each do |exam| %>
      <Row>
        <Cell><Data ss:Type="Number"><%= exam.id %></Data></Cell>
        <Cell><Data ss:Type="Number"><%= exam.subject_id %></Data></Cell>
        <Cell><Data ss:Type="Number"><%= exam.user_id %></Data></Cell>
        <Cell><Data ss:Type="String"><%= exam.status %></Data></Cell>
        <Cell><Data ss:Type="String"><%= exam.question_correct %></Data></Cell>
      </Row>
    <% end %>
    </Table>
  </Worksheet>
</Workbook>

app/views/admin/exams/show.html.erb
<% provide :title, t("exam.title") %>
<h1><%= t "exam.title" %></h1>
<br><br>
<%= render @exam.checked? ? "exam_result" : "exam_check" %>