config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get "help" => "static_pages#help"
  devise_for :users, path_prefix: "d",
    controllers: {omniauth_callbacks: Settings.auth_callback}
  resources :subjects

  resources :users do
    resources :questions
  end
  resources :exams
  namespace :admin do
    root "static_pages#admin_home"
    resources :subjects
    resources :users
    resources :exams
    resources :questions
  end
end

app/models/subject.rb
class Subject < ActiveRecord::Base
  extend FriendlyId
  friendly_id :name, use: :slugged
  has_many :questions, dependent: :destroy
  has_many :exams, dependent: :destroy
  validates :name, presence: true, length: {maximum: 100}
end

app/controllers/admin/subjects_controller.rb
class Admin::SubjectsController < Admin::BaseController
  load_resource

  def index
    @subjects = @subjects.page(params[:page])
      .per Settings.pagination.subjects_per_page
    @exam = Exam.new
  end

  def new
    @subject = Subject.new
  end

  def create
    @subject = Subject.new subject_params
    if @subject.save
      flash[:success] = t "admin.subject.add.success"
      redirect_to admin_subjects_path
    else
      flash.now[:danger] = t "admin.subject.add.fail"
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @subject.update_attributes subject_params
      flash[:success] = t "admin.subject.update.success"
      redirect_to admin_subjects_path
    else
      flash.now[:danger] = t "admin.subject.update.fail"
      render :edit
    end
  end

  def destroy
    if @subject.destroy
      flash[:success] = t "admin.subject.delete.success"
      redirect_to admin_subjects_path
    else
      flash.now[:danger] = t "admin.subject.delete.fail"
      render :index
    end
  end

  private
  def subject_params
    params.require(:subject).permit :name
  end
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  load_and_authorize_resource

  def index
    @subjects = @subjects.page(params[:page])
      .per Settings.pagination.subjects_per_page
    @exam = Exam.new
  end
end

app/views/subjects/_subject.html.erb
<div class="col-md-offset-3 col-md-7 panel panel-default">
  <div class="panel-body">
    <h3><%= link_to subject.name, subject_path(subject) %></h3>
    <p>
      <%= t "created_ago", time: "#{time_ago_in_words subject.created_at}" %>
    </p>
    <%= form_for @exam do |f| %>
      <%= f.hidden_field :subject_id, value: subject.id %>
      <%= f.submit t("exam.start"), class: "btn btn-success" %>
    <% end %>
  </div>
</div>

app/views/subjects/index.html.erb
<% provide :title, t("admin.subject.title") %>
<div class="row">
  <h2 class="h2_title">
    <%= t "admin.subject.title" %>
  </h2>
  <%= render @subjects %>
  <div class="col-md-offset-3 col-md-7">
    <%= paginate @subjects %>
  </div>
</div>