config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get "help" => "static_pages#help"
  devise_for :users, path_prefix: "d",
    controllers: {omniauth_callbacks: Settings.auth_callback}
  resources :subjects

  resources :users do
    resources :questions
  end
  resources :exams
  namespace :admin do
    root "static_pages#admin_home"
    resources :subjects
    resources :users
    resources :exams
    resources :questions
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  enum role: [:user,:admin]

  has_many :questions, dependent: :destroy
  has_many :exams, dependent: :destroy

  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :trackable, :validatable,
    :omniauthable, omniauth_providers: [:facebook, :google_oauth2]

    validates :name, presence: true, length: {maximum: 50}
    validates :chatwork_id, presence: true,
      length: {maximum: 50}, uniqueness: true
    validates :email, length: {maximum: 255}
    validates :role, presence: true

  class << self
    def from_omniauth auth
      where(provider: auth.provider, uid: auth.uid).first_or_create! do |user|
        user.email = auth.info.email
        user.password = Devise.friendly_token[0,20]
        user.name = auth.info.name
      end
    end

    def new_with_session params, session
      super.tap do |user|
        if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
          user.email = data["email"] if user.email.blank?
        end
      end
    end
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController
  load_resource

  def index
    @q = User.ransack params[:q]
    @users = @q.result.page(params[:page])
      .per Settings.pagination.users_per_page
  end

  def update
    if @user.update_attributes user_params
      flash[:success] = t "admin.user.update_success"
    else
      flash[:failed] = t "admin.user.update_fail"
    end
    respond_to do |format|
      format.html {redirect_to admin_users_path}
      format.js
    end
  end

  def destroy
    if @user.destroy
      flash[:success] = t "admin.user.destroy_success"
    else
      flash[:failed] = t "admin.user.destroy_fail"
    end
    respond_to do |format|
      format.html {redirect_to admin_users_path}
      format.js
    end
  end

  private
  def user_params
    params.require(:user).permit :role
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.from_omniauth request.env["omniauth.auth"]

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication
      set_flash_message(:notice, :success, kind: t("user.fb")) if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def google_oauth2
    @user = User.from_omniauth(request.env["omniauth.auth"])
    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication
      set_flash_message(:notice, :success, kind: t("user.gplus")) if is_navigational_format?
    else
      session["devise.google_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  load_and_authorize_resource

  def show
  end
end

app/views/admin/users/_search_form.html.erb
<div class="row">
  <div class="col-md-offset-10">
    <%= search_form_for [:admin, @q] do |f| %>
      <%= f.search_field :name_or_email_cont, placeholder: t("admin.user.search_user"),
        class: "form-control" %>
      <div class="col-md-8">
        <%= f.submit class: "btn btn-info" %>
      </div>
    <% end %>
  </div>
</div>

app/views/admin/users/_user.html.erb
<tr id="user-<%= user.id %>">
  <td><%= link_to user.name, user %></td>
  <td><%= user.email %></td>
  <td>
    <%= form_for [:admin, user], remote: true do |f| %>
      <%= f.hidden_field :role, value: user.admin? ? :user : :admin %>
      <%= f.submit user.admin? ? t("admin.user.set_normal_user") : t("admin.user.set_admin_user"),
        class: "btn btn-success btn-md" unless current_user == user %>
    <% end %>
  </td>
  <td>
    <%= link_to "", admin_user_path(user),
      method: :delete, data: {confirm: t("admin.user.confirm")},
      class: "btn btn-danger glyphicon glyphicon-trash" unless user == current_user %>
  </td>
</tr>

app/views/admin/users/destroy.js.erb
$("#user-<%= @user.id %>").remove();

app/views/admin/users/index.html.erb
<% provide :title, t("admin.user.list_user") %>
<h1><%= t "admin.user.list_user" %></h1>
<br><br>
<p>
  <%= render "search_form" %>
</p>
<div id="section_admin_user">
  <table id="users_record" class="table table-bordered">
    <tbody>
      <tr>
        <th><%= t "admin.name" %></th>
        <th><%= t "admin.email" %></th>
        <th><%= t "admin.change_user_role" %></th>
        <th><%= t "delete" %></th>
      </tr>
      <tr>
        <%= render @users %>
      </tr>
    </tbody>
  </table>
</div>
<%= paginate @users %>

app/views/admin/users/update.js.erb
$("#user-<%= @user.id %>").replaceWith("<%= escape_javascript(render "user", user: @user) %>");